### ISSUE TITLE
Le texte dépasse la largeur de l'écran sur mobile

### ISSUE THREAD

**Issue by ocean-sicard-baux** [romainlebreton/R3.01-DeveloppementWeb#13]
Pour le cours 8 : 

https://romainlebreton.github.io/ProgWeb-CoteServeur/tutorials/tutorial8.html
<img src="https://user-images.githubusercontent.com/60391705/98926190-42125b80-24d7-11eb-8934-d5153d93b60a.png" width="300"> <img src="https://user-images.githubusercontent.com/60391705/98926195-43438880-24d7-11eb-8b64-37481ea0328e.png" width="300">

**Comment by romainlebreton** [comment]
Merci pour l'issue. C'est normalement corrigé.
